# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.8)
{
  description = "VRL for VS Code";

  inputs.nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1";
  outputs = { self, ... }@inputs:
    let
      inherit (inputs.nixpkgs) lib;
      supportedSystems = [ "x86_64-linux" "aarch64-darwin""aarch64-linux" ];
      forEachSupportedSystem = f: lib.genAttrs supportedSystems (system: f {
        pkgs = import inputs.nixpkgs { inherit system; };
      });
    in
    {
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          packages = with pkgs; [
            nodejs
            biome
            vector
            watchexec
          ];
        };
      });

      formatter = forEachSupportedSystem ({ pkgs }: pkgs.nixfmt);
    };
}
