name: Test and publish
on: [push, pull_request]

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/releases/')
        run: yarn publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}