name: Test and publish
on: [push, pull_request]

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install Node.js dependencies
        run: nix develop --command pnpm install
      - name: Run tests
        run: nix develop --command pnpm run test
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/releases/')
        run: nix develop --command pnpm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
